<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageVersion Include="CasCap.Common.Extensions" Version="4.3.6" />
    <PackageVersion Include="CasCap.Common.Serialization.Json" Version="4.3.6" />
    <PackageVersion Include="CasCap.Common.Serialization.MessagePack" Version="4.3.6" />
    <PackageVersion Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.8" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="Serilog" Version="4.3.0" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageVersion Include="StackExchange.Redis" Version="2.8.58" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.3" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.3" />
  </ItemGroup>
</Project>